aliyun/aliyun-odps-jdbc

pom.xml, src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/OdpsQueryResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java
When the client code has its own log4j configuartion , confliction will appear
=> Use java.util.logging instead of log4j

src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java
=> make create table and alter lifecycle into one sql

CHANGELOG.md, pom.xml, src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaData.java, src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java, src/main/java/com/aliyun/odps/jdbc/utils/LoggerFactory.java
Change-Id: Ieca0b809d5bbc360697b86c8f04408b6e876c815
=> remove the dependency of logback

src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java
Reload project when creating connection
62
=> [BUGFIX] Reload project when creating connection

src/main/java/com/aliyun/odps/jdbc/utils/Utils.java
Convert pattern and string to match to lowercase before matching
65
=> [to #65] get table meta should be case insensitive

src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java
=> [to #0] fix typo at OdpsConnection.setAutoCommit

src/main/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaData.java, src/main/java/com/aliyun/odps/jdbc/utils/Utils.java
1. getColumns() now returns partition columns as well
2. bugfix: matchPattern may throw NPE
#72
=> [to #72] getColumns returns partition columns as well

pom.xml, src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaData.java, src/main/java/com/aliyun/odps/jdbc/OdpsForwardResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsPreparedStatement.java, src/main/java/com/aliyun/odps/jdbc/OdpsScollResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java, src/main/java/com/aliyun/odps/jdbc/utils/OdpsLogger.java
1. Update OdpsLogger, set level to WARNING and add log rotate
2. Use extended list table method to improve performance
=> Use extended list table method to improve performance

src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java
=> No exception when cancelling terminated SQL

src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/utils/OdpsFormatter.java, src/main/java/com/aliyun/odps/jdbc/utils/OdpsLogger.java
=> Add file handler only once to each OdpsLogger

src/main/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaData.java, src/main/java/com/aliyun/odps/jdbc/OdpsResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java, src/main/java/com/aliyun/odps/jdbc/OdpsStaticResultSet.java, src/test/java/com/aliyun/odps/jdbc/OdpsStatementTest.java
Implement some unsupported methods
=> Implement unsupported methods

src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java
=> Bugfix: infinite loop when killing new instances

README.md, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcByteArrayTransformer.java
=> feature: support binary

pom.xml, src/main/java/com/aliyun/odps/jdbc/JdbcTest.java, src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java, src/main/java/com/aliyun/odps/jdbc/utils/ConnectionResource.java, src/main/java/com/aliyun/odps/jdbc/utils/Utils.java, src/test/java/com/aliyun/odps/jdbc/utils/UtilsTest.java
=> Support falcon

src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java, src/test/java/com/aliyun/odps/jdbc/OdpsSessionStatementTest.java
=> fix incorrect ret of OdpsStatement#execute

pom.xml, src/main/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaData.java, src/main/java/com/aliyun/odps/jdbc/OdpsForwardResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsResultSet.java
1. remove aspectj maven plugin so that it won't hurt the performance.
2. fix incorrect logs
3. fix deprecated method usage
=> fix: remove aspectj from official releases

README.md, src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/utils/ConnectionResource.java, src/test/java/com/aliyun/odps/jdbc/ConnectionResourceTest.java, src/test/java/com/aliyun/odps/jdbc/utils/ConnectionResourceTest.java
=> doc: update README

src/main/java/com/aliyun/odps/jdbc/OdpsResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsStatement.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/AbstractToJdbcDateTypeTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcDateTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcStringTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcTimeTransfomer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcTimestampTransformer.java, src/test/java/com/aliyun/odps/jdbc/OdpsStatementTest.java
=> feature: set timezone

src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/AbstractToOdpsTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsBigIntTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsBooleanTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsDateTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsDecimalTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsDoubleTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsFloatTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsIntTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsSmallintTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsStringTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsTimeStampTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsTinyintTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsTransformerFactory.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/odps/ToOdpsVarcharTransformer.java, src/test/java/com/aliyun/odps/jdbc/OdpsPreparedStatementTest.java
1. PreparedStatement supports type DATE
2. Add licenses
=> opt: prepare statment supports type DATE

src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java, src/main/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaData.java, src/main/java/com/aliyun/odps/jdbc/OdpsResultSet.java, src/main/java/com/aliyun/odps/jdbc/utils/ConnectionResource.java, src/test/java/com/aliyun/odps/jdbc/ConnectionResourceTest.java, src/test/java/com/aliyun/odps/jdbc/OdpsDatabaseMetaDataTest.java, src/test/resources/odps_config.ini
The following methods return not only the current project but also all the available projects, including the MaxCompute public dataset project 'MAXCOMPUTE_PUBLIC_DATA'.
DatabaseMetaData#getCatalogs()
DatabaseMetaData#getSchemas()
DatabaseMetaData#getSchemas(String, String)
=> feature: support multi projects

pom.xml, src/test/java/com/aliyun/odps/jdbc/TestManager.java
=> add autoSelectLimit and enableLimit in test manager

src/main/java/com/aliyun/odps/jdbc/OdpsResultSet.java, src/main/java/com/aliyun/odps/jdbc/OdpsResultSetMetaData.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/AbstractToJdbcDateTypeTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/AbstractToJdbcTransformer.java, src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcStringTransformer.java, src/test/java/com/aliyun/odps/jdbc/OdpsResultSetTest.java
=> complex odps typeinfo supported in resultSet.getString. format in instance tunnel same with cmd.

src/main/java/com/aliyun/odps/jdbc/utils/ConnectionResource.java, src/test/java/com/aliyun/odps/jdbc/ConnectionResourceTest.java
=> fix connect string logConfFile typo

src/main/java/com/aliyun/odps/jdbc/utils/transformer/to/jdbc/ToJdbcStringTransformer.java
=> fix timestamp format to string problem, nano part
